# You can use this file to create a conda environment for this pipeline:

name: connor-lab-nextflow_qc-0.1
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - minimap2=2.17
  - samtools=1.9
  - trim-galore=0.6.4
  - bbmap=38.70
  - centrifuge=1.0.4_beta
  - krona=2.7.1
  - fastqc=0.11.8
  - multiqc=1.7
